import ast
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_runtime_package_has_expected_layer_directories():
    expected = {
        "api",
        "core",
        "data",
        "engine",
        "heuristics",
        "imports",
        "integrations",
        "tools",
        "web",
    }

    present = {path.name for path in (ROOT / "ode").iterdir() if path.is_dir()}

    assert expected <= present


def test_runtime_code_does_not_import_top_level_experimental_areas():
    forbidden_roots = {"imports", "prototypes"}
    offenders: list[str] = []

    for path in (ROOT / "ode").rglob("*.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.split(".", 1)[0]
                    if root in forbidden_roots:
                        offenders.append(f"{path.relative_to(ROOT)} imports {alias.name}")
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                root = node.module.split(".", 1)[0]
                if root in forbidden_roots:
                    offenders.append(f"{path.relative_to(ROOT)} imports from {node.module}")

    assert offenders == []


def test_optional_web_app_stays_on_service_command_boundary():
    offenders: list[str] = []
    forbidden_prefixes = (
        "ode.core",
        "ode.data",
        "ode.engine",
        "ode.heuristics",
        "ode.services",
        "ode.service",
        "ode.tools",
    )

    def is_forbidden(module: str) -> bool:
        return any(module == prefix or module.startswith(f"{prefix}.") for prefix in forbidden_prefixes)

    for path in (ROOT / "web").rglob("*.py"):
        if "tests" in path.relative_to(ROOT).parts:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if is_forbidden(alias.name):
                        offenders.append(f"{path.relative_to(ROOT)} imports {alias.name}")
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                if is_forbidden(node.module):
                    offenders.append(f"{path.relative_to(ROOT)} imports from {node.module}")

    assert offenders == []


def test_default_pytest_excludes_optional_web_tests():
    # The optional web/ extension must stay removable: it must not wire its
    # tests into the root pyproject.toml. web/tests runs via `pytest web/tests`.
    config = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))

    testpaths = config["tool"]["pytest"]["ini_options"]["testpaths"]

    assert "tests" in testpaths
    assert "web/tests" not in testpaths


def test_git_does_not_track_runtime_artifacts():
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    tracked = result.stdout.splitlines()
    artifacts = [
        path
        for path in tracked
        if "__pycache__" in path or ".pytest_cache" in path or path.endswith(".pyc")
    ]

    assert artifacts == []


def test_artifact_write_plan_blocks_ambiguous_overwrite(tmp_path):
    from ode.core.artifacts import plan_artifact_write

    target = tmp_path / "report.md"
    target.write_text("# User notes\n", encoding="utf-8")

    plan = plan_artifact_write("report.md", root=tmp_path, purpose="DBS report")

    assert plan.decision == "conflict"
    assert plan.reason == "existing_file_is_user_authored_or_ambiguous"
    assert plan.resolved_path.endswith("report-v2.md")
    assert str(target) in plan.conflicts


def test_artifact_write_plan_updates_only_opted_in_generated_files(tmp_path):
    from ode.core.artifacts import plan_artifact_write

    target = tmp_path / "report.md"
    target.write_text("<!-- Generated by ODE -->\n# Report\n", encoding="utf-8")

    cautious = plan_artifact_write("report.md", root=tmp_path, purpose="DBS report")
    opted_in = plan_artifact_write(
        "report.md",
        root=tmp_path,
        purpose="DBS report",
        allow_generated_update=True,
    )

    assert cautious.decision == "version"
    assert cautious.resolved_path.endswith("report-v2.md")
    assert opted_in.decision == "update_generated"
    assert opted_in.resolved_path == str(target.resolve())


def test_artifact_write_plan_versions_similar_artifacts(tmp_path):
    from ode.core.artifacts import plan_artifact_write

    existing = tmp_path / "repair-map-v2.md"
    existing.write_text("<!-- Generated by ODE -->\n# Repair Map\n", encoding="utf-8")

    plan = plan_artifact_write("repair-map.md", root=tmp_path, purpose="AI hardware map")

    assert plan.decision == "version"
    assert plan.reason == "similar_artifact_already_exists"
    assert plan.resolved_path.endswith("repair-map-v3.md")
    assert str(existing) in plan.conflicts


def test_artifact_write_plan_blocks_outside_root(tmp_path):
    from ode.core.artifacts import plan_artifact_write

    plan = plan_artifact_write(tmp_path.parent / "outside.md", root=tmp_path)

    assert plan.decision == "blocked"
    assert plan.reason == "target_outside_root"
