import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "hardware-engineer-global-opportunity-scan.md"
CONTRACT = ROOT / "docs" / "09-opportunity-scan-quality-contract.md"
TEMPLATE = ROOT / "docs" / "opportunity-scan-template.md"
VALUE_CHAIN_MAP = (
    ROOT
    / "docs"
    / "assets"
    / "opportunity_maps"
    / "hardware-engineer-global-value-chain-map.svg"
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _section(text: str, heading: str) -> str:
    start = text.index(heading)
    next_heading = text.find("\n## ", start + len(heading))
    if next_heading == -1:
        return text[start:]
    return text[start:next_heading]


def test_quality_contract_and_template_exist_with_required_gates():
    contract = _read(CONTRACT)
    template = _read(TEMPLATE)

    for gate in [
        "Reader Contract",
        "Opportunity Map Gate",
        "Evidence Gate",
        "DBS Dialogue Gate",
        "Candidate Ranking Gate",
        "Action Gate",
        "Artifact Gate",
        "Done Definition",
    ]:
        assert gate in contract

    for visual_requirement in [
        "human-facing visual map",
        "machine-readable structured map",
        "At least 20 plotted opportunities",
        "two-layer mapping",
    ]:
        assert visual_requirement in contract

    for required_section in [
        "Decision Summary",
        "Whole Opportunity Map",
        "Evidence Ledger",
        "Candidate Ranking",
        "DBS Dialogue",
        "Action Plan",
        "Appendix",
    ]:
        assert required_section in template

    assert "image2-generated bitmap" in template
    assert "quadrantChart" in template


def test_hardware_scan_has_whole_map_before_single_recommendation():
    text = _read(REPORT)
    map_section = _section(text, "## 5. 全局机会地图")

    assert text.startswith("<!-- Generated by ODE -->")
    assert VALUE_CHAIN_MAP.exists()
    assert "assets/opportunity_maps/hardware-engineer-global-value-chain-map.svg" in map_section
    assert map_section.count("```mermaid") >= 2
    assert "flowchart LR" in map_section
    assert "quadrantChart" in map_section
    assert "### 候选机会池" in map_section

    quadrant_block = re.search(r"quadrantChart(?P<body>.*?)```", map_section, re.S)
    assert quadrant_block is not None
    plotted_points = re.findall(r'"[^"]+": \[[0-9.]+, [0-9.]+\]', quadrant_block.group("body"))
    assert len(plotted_points) >= 20

    candidate_rows = [
        line
        for line in map_section.splitlines()
        if line.startswith("| ")
        and "---" not in line
        and "Candidate" not in line
        and "机会" not in line
        and "层级" not in line
    ]

    assert len(candidate_rows) >= 24
    assert "Prototype-to-Production Readiness Review" in map_section
    assert "White-label Hardware Export" in map_section
    assert "Self-owned Hardware Product" in map_section
    assert "General AI Hardware Platform" in map_section
    assert "Marketplace for Hardware Suppliers" in map_section
    assert "地图上保留 26 个候选机会" in map_section


def test_hardware_scan_keeps_evidence_breadth_and_separation():
    text = _read(REPORT)

    assert "本地 ODE 扫描结果" in text
    assert "`150` raw signals" in text
    assert "`39` kept signals" in text
    assert "证据账本" in text
    assert "宏观报告不能直接证明小团队机会" in text

    required_sources = [
        "Cisco",
        "KPMG",
        "Deloitte",
        "S&P Global",
        "Global Electronics Association",
        "Texcel",
        "Evertiq",
        "ServicePower",
        "Your Europe",
        "FCC",
    ]
    for source in required_sources:
        assert source in text

    external_links = re.findall(r"https?://[^\)\s]+", text)
    assert len(set(external_links)) >= 12


def test_hardware_scan_has_deep_dbs_dialogue():
    text = _read(REPORT)
    dbs_section = _section(text, "## 7. 深度 DBS 对话记录")
    rounds = re.findall(r"### Round \d", dbs_section)

    assert len(rounds) >= 6
    assert dbs_section.count("Builder") >= len(rounds)
    assert dbs_section.count("Challenger") >= len(rounds)
    assert dbs_section.count("Revision") >= len(rounds)
    assert dbs_section.count("Judge") >= len(rounds)
    assert "Verdict: Validate Payment Now" in dbs_section


def test_hardware_scan_closes_with_executable_validation_plan():
    text = _read(REPORT)

    for required in [
        "## 8. 7 天行动计划",
        "## 9. 30 天路线",
        "Pass",
        "Fail",
        "USD 99",
        "30 天不做",
        "不做完整 SaaS",
    ]:
        assert required in text

    assert "python -m ode pain" in text
    assert "python -m ode explore" in text
    assert "python -m ode cases" in text
