"""Artifact governance helpers.

These helpers do not write files. They make the write decision explicit before
an analysis workflow creates a report, export, render, or other generated file.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterable


GENERATED_MARKERS = (
    "Generated by ODE",
    "generated_by: ode",
    "generated-by: ode",
    "ODE_GENERATED",
)


@dataclass(frozen=True)
class ArtifactWritePlan:
    requested_path: str
    resolved_path: str
    decision: str
    reason: str
    checks: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    metadata: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


def plan_artifact_write(
    target_path: str | Path,
    *,
    root: str | Path | None = None,
    purpose: str = "",
    allow_generated_update: bool = False,
    generated_markers: Iterable[str] = GENERATED_MARKERS,
) -> ArtifactWritePlan:
    """Return the safe write plan for a generated artifact path.

    Decisions:
    - ``create``: target does not exist and no similar sibling was found.
    - ``update_generated``: target exists, looks generated, and overwrite was opted in.
    - ``version``: create a versioned sibling instead of overwriting.
    - ``conflict``: target is user-authored or ambiguous; caller must resolve.
    - ``blocked``: target is outside root or points at a directory.
    """

    root_path = Path(root or Path.cwd()).resolve()
    requested = Path(target_path)
    target = requested if requested.is_absolute() else root_path / requested
    target = target.resolve()
    checks = [
        "resolved_target_path",
        "checked_target_within_root",
        "checked_existing_path",
        "checked_similar_artifacts",
        "classified_overwrite_risk",
    ]
    metadata = {
        "purpose": purpose,
        "ownership": "generated_artifact",
        "root": str(root_path),
    }

    if not _is_relative_to(target, root_path):
        return ArtifactWritePlan(
            requested_path=str(requested),
            resolved_path=str(target),
            decision="blocked",
            reason="target_outside_root",
            checks=checks,
            metadata=metadata,
        )

    if target.exists() and target.is_dir():
        return ArtifactWritePlan(
            requested_path=str(requested),
            resolved_path=str(target),
            decision="blocked",
            reason="target_is_directory",
            checks=checks,
            conflicts=[str(target)],
            metadata=metadata,
        )

    if target.exists():
        if _looks_generated(target, generated_markers):
            if allow_generated_update:
                return ArtifactWritePlan(
                    requested_path=str(requested),
                    resolved_path=str(target),
                    decision="update_generated",
                    reason="existing_generated_artifact_update_allowed",
                    checks=checks,
                    conflicts=[str(target)],
                    metadata=metadata,
                )
            versioned = _next_versioned_path(target)
            return ArtifactWritePlan(
                requested_path=str(requested),
                resolved_path=str(versioned),
                decision="version",
                reason="existing_generated_artifact_requires_explicit_update",
                checks=checks,
                conflicts=[str(target)],
                metadata=metadata,
            )

        versioned = _next_versioned_path(target)
        return ArtifactWritePlan(
            requested_path=str(requested),
            resolved_path=str(versioned),
            decision="conflict",
            reason="existing_file_is_user_authored_or_ambiguous",
            checks=checks,
            conflicts=[str(target)],
            metadata=metadata,
        )

    similar = _similar_artifacts(target)
    if similar:
        versioned = _next_versioned_path(target)
        return ArtifactWritePlan(
            requested_path=str(requested),
            resolved_path=str(versioned),
            decision="version",
            reason="similar_artifact_already_exists",
            checks=checks,
            conflicts=[str(path) for path in similar],
            metadata=metadata,
        )

    return ArtifactWritePlan(
        requested_path=str(requested),
        resolved_path=str(target),
        decision="create",
        reason="no_existing_or_similar_artifact",
        checks=checks,
        metadata=metadata,
    )


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _looks_generated(path: Path, markers: Iterable[str]) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")[:4096]
    except OSError:
        return False
    return any(marker in text for marker in markers)


def _similar_artifacts(target: Path) -> list[Path]:
    if not target.parent.exists():
        return []
    return sorted(
        path
        for path in target.parent.glob(f"{target.stem}*{target.suffix}")
        if path != target and path.is_file()
    )


def _next_versioned_path(target: Path) -> Path:
    for index in range(2, 1000):
        candidate = target.with_name(f"{target.stem}-v{index}{target.suffix}")
        if not candidate.exists():
            return candidate
    raise RuntimeError(f"No available versioned artifact path for {target}")
